development:
  adapter: redis
  url: <%= Rails.application.credentials.config[:REDIS_URL] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.config[:REDIS_URL] %>
  channel_prefix: medici_production
